/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const VegetableId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DailySales = IDL.Record({
  'date' : IDL.Int,
  'totalSales' : IDL.Float64,
});
export const AccountingSummary = IDL.Record({
  'inDeliveryOrders' : IDL.Nat,
  'cancelledOrders' : IDL.Nat,
  'totalOrders' : IDL.Nat,
  'pendingOrders' : IDL.Nat,
  'dailyBreakdown' : IDL.Vec(DailySales),
  'totalRevenue' : IDL.Float64,
  'deliveredOrders' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'inDelivery' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
});
export const Time = IDL.Int;
export const CustomerId = IDL.Nat;
export const OrderItem = IDL.Record({
  'vegetableId' : VegetableId,
  'quantity' : IDL.Float64,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'totalAmount' : IDL.Float64,
  'address' : IDL.Text,
  'timestamp' : Time,
  'customerId' : CustomerId,
  'items' : IDL.Vec(OrderItem),
});
export const Vegetable = IDL.Record({
  'id' : VegetableId,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'pricePerUnit' : IDL.Float64,
  'stock' : IDL.Float64,
  'imageUrl' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addVegetable' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Opt(IDL.Text)],
      [VegetableId],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAccountingSummary' : IDL.Func([], [AccountingSummary], ['query']),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomerOrders' : IDL.Func([CustomerId], [IDL.Vec(Order)], ['query']),
  'getCustomerProfile' : IDL.Func([CustomerId], [UserProfile], ['query']),
  'getOrder' : IDL.Func([OrderId], [Order], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVegetable' : IDL.Func([VegetableId], [Vegetable], ['query']),
  'getVegetables' : IDL.Func([], [IDL.Vec(Vegetable)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginCustomer' : IDL.Func([IDL.Text, IDL.Text], [CustomerId], []),
  'placeOrder' : IDL.Func(
      [CustomerId, IDL.Vec(OrderItem), IDL.Text],
      [OrderId],
      [],
    ),
  'registerCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [CustomerId],
      [],
    ),
  'removeVegetable' : IDL.Func([VegetableId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
  'updateVegetable' : IDL.Func(
      [
        VegetableId,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const VegetableId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DailySales = IDL.Record({
    'date' : IDL.Int,
    'totalSales' : IDL.Float64,
  });
  const AccountingSummary = IDL.Record({
    'inDeliveryOrders' : IDL.Nat,
    'cancelledOrders' : IDL.Nat,
    'totalOrders' : IDL.Nat,
    'pendingOrders' : IDL.Nat,
    'dailyBreakdown' : IDL.Vec(DailySales),
    'totalRevenue' : IDL.Float64,
    'deliveredOrders' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'phone' : IDL.Text });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'inDelivery' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const Time = IDL.Int;
  const CustomerId = IDL.Nat;
  const OrderItem = IDL.Record({
    'vegetableId' : VegetableId,
    'quantity' : IDL.Float64,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'totalAmount' : IDL.Float64,
    'address' : IDL.Text,
    'timestamp' : Time,
    'customerId' : CustomerId,
    'items' : IDL.Vec(OrderItem),
  });
  const Vegetable = IDL.Record({
    'id' : VegetableId,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'pricePerUnit' : IDL.Float64,
    'stock' : IDL.Float64,
    'imageUrl' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addVegetable' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Opt(IDL.Text)],
        [VegetableId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAccountingSummary' : IDL.Func([], [AccountingSummary], ['query']),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomerOrders' : IDL.Func([CustomerId], [IDL.Vec(Order)], ['query']),
    'getCustomerProfile' : IDL.Func([CustomerId], [UserProfile], ['query']),
    'getOrder' : IDL.Func([OrderId], [Order], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVegetable' : IDL.Func([VegetableId], [Vegetable], ['query']),
    'getVegetables' : IDL.Func([], [IDL.Vec(Vegetable)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginCustomer' : IDL.Func([IDL.Text, IDL.Text], [CustomerId], []),
    'placeOrder' : IDL.Func(
        [CustomerId, IDL.Vec(OrderItem), IDL.Text],
        [OrderId],
        [],
      ),
    'registerCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [CustomerId],
        [],
      ),
    'removeVegetable' : IDL.Func([VegetableId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
    'updateVegetable' : IDL.Func(
        [
          VegetableId,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };