/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccountingSummary {
  'inDeliveryOrders' : bigint,
  'cancelledOrders' : bigint,
  'totalOrders' : bigint,
  'pendingOrders' : bigint,
  'dailyBreakdown' : Array<DailySales>,
  'totalRevenue' : number,
  'deliveredOrders' : bigint,
}
export type CustomerId = bigint;
export interface DailySales { 'date' : bigint, 'totalSales' : number }
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'totalAmount' : number,
  'address' : string,
  'timestamp' : Time,
  'customerId' : CustomerId,
  'items' : Array<OrderItem>,
}
export type OrderId = bigint;
export interface OrderItem { 'vegetableId' : VegetableId, 'quantity' : number }
export type OrderStatus = { 'inDelivery' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string, 'phone' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vegetable {
  'id' : VegetableId,
  'name' : string,
  'unit' : string,
  'pricePerUnit' : number,
  'stock' : number,
  'imageUrl' : [] | [string],
}
export type VegetableId = bigint;
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addVegetable' : ActorMethod<
    [string, string, number, number, [] | [string]],
    VegetableId
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAccountingSummary' : ActorMethod<[], AccountingSummary>,
  'getAllCustomers' : ActorMethod<[], Array<UserProfile>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomerOrders' : ActorMethod<[CustomerId], Array<Order>>,
  'getCustomerProfile' : ActorMethod<[CustomerId], UserProfile>,
  'getOrder' : ActorMethod<[OrderId], Order>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVegetable' : ActorMethod<[VegetableId], Vegetable>,
  'getVegetables' : ActorMethod<[], Array<Vegetable>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginCustomer' : ActorMethod<[string, string], CustomerId>,
  'placeOrder' : ActorMethod<[CustomerId, Array<OrderItem>, string], OrderId>,
  'registerCustomer' : ActorMethod<[string, string, string], CustomerId>,
  'removeVegetable' : ActorMethod<[VegetableId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
  'updateVegetable' : ActorMethod<
    [VegetableId, string, string, number, number, [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];